### ISSUE TITLE
Tresarcoin will not work   

### ISSUE THREAD

**Issue by pfreak2000** [wellenreiter01/p2pool-neoscrypt#10]
i use Windows 10 an got this failur if i start the pool. can anyone help me, other p2pools run without problems

2017-12-19 16:37:43.955000 p2pool (version 6d59072)
2017-12-19 16:37:43.955000
2017-12-19 16:37:43.955000 Testing daemon RPC connection to 'http://127.0.0.1:17299/' with username '*******'...
2017-12-19 16:37:44.033000     ...success!
2017-12-19 16:37:44.033000     Current block hash: 34dea7dbdedd4c9322e74af56c5c68217e3cd826e4902b1ce859ef745d1asd9b0
2017-12-19 16:37:44.033000     Current block height: 151043
2017-12-19 16:37:44.033000
2017-12-19 16:37:44.033000 Testing coin daemon P2P connection to '127.0.0.1:17298'...
2017-12-19 16:37:44.158000     ...success!
2017-12-19 16:37:44.158000
2017-12-19 16:37:44.158000 Determining payout address...
2017-12-19 16:37:44.158000     ...success! Payout address: xxxxxxxxxxxxxxxxxxxxxxxxx
2017-12-19 16:37:44.158000
2017-12-19 16:37:44.158000 Loading shares...
2017-12-19 16:37:44.158000     ...done loading 0 shares (0 verified)!
2017-12-19 16:37:44.158000
2017-12-19 16:37:44.158000 Initializing work...
Error while requesting best block header:
Traceback (most recent call last):
Failure: twisted.internet.defer.TimeoutError: in ReplyMatcher

**Comment by pfreak2000** [comment]
Error getting work from bitcoind:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 1442, in gotResult
    _inlineCallbacks(r, g, deferred)
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "C:\Python27\lib\site-packages\twisted\python\failure.py", line 393, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
--- <exception caught here> ---
  File "C:\Users\p2pool\Desktop\P2Pool Daten\p2pool-neoscrypt\p2pool\util\deferral.py", line 41, in f
    result = yield func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "C:\Users\p2pool\Desktop\P2Pool Daten\p2pool-neoscrypt\p2pool\bitcoin\helper.py", line 61, in getwork
    transactions=map(bitcoin_data.tx_type.unpack, packed_transactions),
  File "C:\Users\p2pool\Desktop\P2Pool Daten\p2pool-neoscrypt\p2pool\util\pack.py", line 63, in unpack
    obj = self._unpack(data, ignore_trailing)
  File "C:\Users\p2pool\Desktop\P2Pool Daten\p2pool-neoscrypt\p2pool\util\pack.py", line 42, in _unpack
    obj, (data2, pos) = self.read((data, 0))
  File "C:\Users\p2pool\Desktop\P2Pool Daten\p2pool-neoscrypt\p2pool\util\pack.py", line 295, in read
    item[key], file = type_.read(file)
  File "C:\Users\p2pool\Desktop\P2Pool Daten\p2pool-neoscrypt\p2pool\util\pack.py", line 171, in read
    res[i], file = self.type.read(file)
  File "C:\Users\p2pool\Desktop\P2Pool Daten\p2pool-neoscrypt\p2pool\util\pack.py", line 295, in read
    item[key], file = type_.read(file)
  File "C:\Users\p2pool\Desktop\P2Pool Daten\p2pool-neoscrypt\p2pool\util\pack.py", line 132, in read
    return read(file, length)
  File "C:\Users\p2pool\Desktop\P2Pool Daten\p2pool-neoscrypt\p2pool\util\pack.py", line 16, in read
    raise EarlyEnd()
p2pool.util.pack.EarlyEnd:
